### ISSUE TITLE
 Burnex not found. Please add it to your dependencies to use :burner and :check_mx_record checks.

### ISSUE THREAD

**Issue by ghenry** [achedeuzot/ecto_commons#107]
Hi,

Got a weird one. I do have ` {:burnex, "~> 3.1.0"},` in my `mix.exs` and this works:

```
iex(10)> Burnex.is_burner?("ghenry@testing.com")
false
```

but am getting:

```
** (RuntimeError) Burnex not found. Please add it to your dependencies to use :burner and :check_mx_record checks.
    (ecto_commons 0.3.6) lib/validators/email.ex:121: EctoCommons.EmailValidator.do_validate_email/2
    (ecto_commons 0.3.6) lib/validators/email.ex:86: anonymous fn/5 in EctoCommons.EmailValidator.validate_email/3
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_commons 0.3.6) lib/validators/email.ex:85: anonymous fn/4 in EctoCommons.EmailValidator.validate_email/3
    (ecto 3.12.4) lib/ecto/changeset.ex:2421: Ecto.Changeset.validate_change/3
    (sentrypeer 1.0.0) lib/sentrypeer/contact_form/contact.ex:41: Sentrypeer.ContactForm.Contact.changeset/2
    (sentrypeer 1.0.0) lib/sentrypeer_web/live/contact_live/form_component.ex:64: SentrypeerWeb.ContactLive.FormComponent.handle_event/3
```

I've not changed any code lately. Any ideas?

Thanks.

**Comment by ghenry** [comment]
Odd. Think it was clearing out `_build` that did it...or...
